---
general:
  buildTool: "mta"
service:
  buildToolVersion: "MBTJ17N18"
  stages:
    Acceptance:
      cfCredentialsId: "deploy-to-cf"
    Release:
      cfCredentialsId: "deploy-to-cf"
stages:
  Build:
    mavenExecuteStaticCodeChecks: false
    npmExecuteLint: false
  Acceptance:
    cfApiEndpoint: "https://api.cf.us10-001.hana.ondemand.com"
    cfOrg: "d0a64f88trial"
    cfSpace: "dev"
    deployType: "standard"
    cloudFoundryDeploy: true
    npmExecuteEndToEndTests: false
  Malware Scan:
    malwareExecuteScan: false
  Release:
    tmsExport: true
    tmsUpload: true
    cfApiEndpoint: "https://api.cf.us10-001.hana.ondemand.com"
    cfOrg: "d0a64f88trial"
    cfSpace: "dev"
    deployType: "standard"
    cloudFoundryDeploy: true
  Additional Unit Tests:
    npmExecuteScripts: false
  Compliance:
    sonarExecuteScan: false
steps:
  cloudFoundryDeploy:
    mtaDeployParameters: "-f --version-rule ALL"
  artifactPrepareVersion:
    versioningType: "cloud_noTag"
  tmsUpload:
    nodeName: "QAS"
    credentialsId: "transportmgmt"
