---
general:
  buildTool: "mta"
service:
  buildToolVersion: "MBTJ17N18"
  stages:
    Acceptance:
      cfCredentialsId: "deploy-to-cf"
    Release:
      cfCredentialsId: "deploy-to-cf"
stages:
  Build:
    mavenExecuteStaticCodeChecks: false
    npmExecuteLint: true
  Acceptance:
    cfApiEndpoint: "https://api.cf.us10-001.hana.ondemand.com"
    cfOrg: "Dwyer Instruments LLC_pbc-dev-lbyb32ei"
    cfSpace: "DEV"
    deployType: "standard"
    cloudFoundryDeploy: true
    npmExecuteEndToEndTests: true
  Malware Scan:
    malwareExecuteScan: false
  Release:
    tmsExport: true
    tmsUpload: false
    cfApiEndpoint: "https://api.cf.us10-001.hana.ondemand.com"
    cfOrg: "Dwyer Instruments LLC_pbc-dev-lbyb32ei"
    cfSpace: "DEV"
    deployType: "standard"
    cloudFoundryDeploy: true
  Additional Unit Tests:
    npmExecuteScripts: false
  Compliance:
    sonarExecuteScan: false
steps:
  cloudFoundryDeploy:
    mtaDeployParameters: "-f --version-rule ALL"
  tmsExport:
    nodeName: "QA"
    credentialsId: "tmsauth"
  artifactPrepareVersion:
    versioningType: "cloud_noTag"
